// The desktop half of sign-in: a one-shot HTTP listener on the loopback
// interface that receives the one-time token the server hands back.
//
// This replaces a werewolf:// deep link. A custom scheme needs the OS to
// resolve it, the browser to agree to launch it, and a user gesture to allow
// it — three things outside our control, each of which fails silently. A
// loopback redirect is an ordinary HTTP navigation the browser simply follows,
// which is what RFC 8252 section 7.3 recommends for native apps and what every
// desktop CLI that logs in through a browser actually does.
//
// Security properties this file is responsible for:
//   - bind 127.0.0.1 only, NEVER 0.0.0.0, so nothing off-device can reach it
//   - accept exactly one successful callback, then stop listening
//   - stop listening after a timeout even if the browser never arrives
//   - verify the `state` the server echoes back, in constant time, so another
//     process on this machine cannot hand us a token of its own choosing
//
// The `state` is generated by the caller (the webview, via crypto.getRandomValues)
// rather than here, which keeps this file free of a random-number dependency.

use std::io::{BufRead, BufReader, Read, Write};
use std::net::{Ipv4Addr, SocketAddrV4, TcpListener, TcpStream};
use std::thread;
use std::time::{Duration, Instant};

use tauri::{AppHandle, Emitter, Runtime};

/// How long to wait for the browser before giving up and freeing the port.
const LISTEN_TIMEOUT: Duration = Duration::from_secs(300);
/// How often the accept loop wakes to re-check the deadline.
const POLL_INTERVAL: Duration = Duration::from_millis(50);
/// A request line longer than this is not one of ours.
const MAX_REQUEST_LINE: u64 = 8 * 1024;

/// The event the webview listens for. Payload is [`AuthCallback`].
pub const AUTH_CALLBACK_EVENT: &str = "auth://callback";

#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize)]
pub struct AuthCallback {
  /// The one-time token to exchange, when the handoff succeeded.
  pub ott: Option<String>,
  /// A machine-readable failure code, when it did not.
  pub code: Option<String>,
}

impl AuthCallback {
  fn token(ott: String) -> Self {
    Self { ott: Some(ott), code: None }
  }
  fn failed(code: &str) -> Self {
    Self { ott: None, code: Some(code.to_string()) }
  }
}

/// Compare two secrets without leaking their contents through timing.
fn constant_time_eq(a: &str, b: &str) -> bool {
  let (a, b) = (a.as_bytes(), b.as_bytes());
  if a.len() != b.len() {
    return false;
  }
  let mut diff = 0u8;
  for (x, y) in a.iter().zip(b.iter()) {
    diff |= x ^ y;
  }
  diff == 0
}

/// What the browser sees once it has delivered the token. It is a dead end on
/// purpose: the app is already signing in behind it.
fn respond(stream: &mut TcpStream, status: &str, body: &str) {
  let response = format!(
    "HTTP/1.1 {status}\r\n\
     content-type: text/html; charset=utf-8\r\n\
     cache-control: no-store\r\n\
     connection: close\r\n\
     content-length: {}\r\n\r\n{body}",
    body.len()
  );
  let _ = stream.write_all(response.as_bytes());
  let _ = stream.flush();
}

fn done_page(locale: &str) -> String {
  // Renders outside the app, in whatever browser the user happens to have
  // open, so the app has to tell us its language: the browser's own setting is
  // regularly a different one, and switching languages mid-sign-in is jarring.
  let (lang, body) = if locale == "es" {
    ("es", "Sesión iniciada. Ya puedes cerrar esta pestaña.")
  } else {
    ("en", "Signed in. You can close this tab.")
  };
  format!(
    "<!doctype html><html lang=\"{lang}\"><head><meta charset=\"utf-8\">\
<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\
<title>Werewolf</title><style>body{{margin:0;min-height:100vh;display:flex;\
align-items:center;justify-content:center;background:#14110f;color:#e9e5da;\
font:16px/1.5 system-ui,sans-serif}}</style></head>\
<body><p>{body}</p></body></html>"
  )
}

/// Read the request target from the first line of an HTTP request.
fn request_target(stream: &TcpStream) -> Option<String> {
  let mut line = String::new();
  let mut reader = BufReader::new(stream.try_clone().ok()?).take(MAX_REQUEST_LINE);
  reader.read_line(&mut line).ok()?;
  // "GET /callback?ott=...&state=... HTTP/1.1"
  line.split_whitespace().nth(1).map(|target| target.to_string())
}

/// Pull `ott` and `state` out of the request target.
fn parse_callback(target: &str) -> (Option<String>, Option<String>, Option<String>) {
  // A relative target has no base, so give the parser one it can throw away.
  let Ok(url) = url::Url::parse("http://127.0.0.1").and_then(|base| base.join(target)) else {
    return (None, None, None);
  };
  let mut ott = None;
  let mut state = None;
  let mut error = None;
  for (key, value) in url.query_pairs() {
    match key.as_ref() {
      "ott" => ott = Some(value.into_owned()),
      "state" => state = Some(value.into_owned()),
      "error" => error = Some(value.into_owned()),
      _ => {}
    }
  }
  (ott, state, error)
}

/// Wait for the one callback we care about and answer everything else. Split
/// out of the command so it can be driven over a real socket by a test: this
/// is where the state check lives, and a state check that is never exercised
/// is a state check that does not work.
fn serve_once(
  listener: &TcpListener,
  expected_state: &str,
  locale: &str,
  deadline: Instant,
) -> AuthCallback {
  loop {
    if Instant::now() >= deadline {
      return AuthCallback::failed("HANDOFF_TIMEOUT");
    }

    let mut stream = match listener.accept() {
      Ok((stream, _)) => stream,
      Err(ref error) if error.kind() == std::io::ErrorKind::WouldBlock => {
        thread::sleep(POLL_INTERVAL);
        continue;
      }
      Err(_) => return AuthCallback::failed("HANDOFF_FAILED"),
    };
    let _ = stream.set_read_timeout(Some(Duration::from_secs(5)));
    let _ = stream.set_write_timeout(Some(Duration::from_secs(5)));

    let Some(target) = request_target(&stream) else {
      respond(&mut stream, "400 Bad Request", "");
      continue;
    };
    let (ott, echoed_state, error) = parse_callback(&target);

    // Anything that is not our callback (a favicon probe, a stray curl) is
    // answered and ignored; the listener stays up for the real one.
    if ott.is_none() && error.is_none() {
      respond(&mut stream, "404 Not Found", "");
      continue;
    }

    // The state check is the whole reason another local process cannot
    // complete our sign-in with a token it chose.
    if !echoed_state.as_deref().is_some_and(|echoed| constant_time_eq(echoed, expected_state)) {
      respond(&mut stream, "403 Forbidden", "");
      continue;
    }

    respond(&mut stream, "200 OK", &done_page(locale));
    return match (ott, error) {
      (Some(ott), _) => AuthCallback::token(ott),
      (None, Some(code)) => AuthCallback::failed(&code),
      (None, None) => AuthCallback::failed("HANDOFF_FAILED"),
    };
  }
}

/// Bind a loopback port and wait, on a background thread, for the server to
/// redirect the browser to it. Returns the port the caller must send to
/// `/api/auth-start`. Emits [`AUTH_CALLBACK_EVENT`] exactly once.
#[tauri::command]
pub fn start_auth_handoff<R: Runtime>(
  app: AppHandle<R>,
  state: String,
  locale: String,
) -> Result<u16, String> {
  if state.len() < 32 {
    // Not a real nonce; refuse rather than stand up a listener that cannot
    // tell our own callback from anyone else's.
    return Err("STATE_TOO_SHORT".to_string());
  }

  // LOOPBACK ONLY. Binding 0.0.0.0 here would put a token-accepting endpoint
  // on every interface of the machine.
  let address = SocketAddrV4::new(Ipv4Addr::LOCALHOST, 0);
  let listener = TcpListener::bind(address).map_err(|error| format!("BIND_FAILED: {error}"))?;
  let port = listener.local_addr().map_err(|error| format!("BIND_FAILED: {error}"))?.port();
  listener
    .set_nonblocking(true)
    .map_err(|error| format!("BIND_FAILED: {error}"))?;

  log::info!(target: "werewolf::auth", "loopback handoff listening on 127.0.0.1:{port}");

  thread::spawn(move || {
    let result = serve_once(&listener, &state, &locale, Instant::now() + LISTEN_TIMEOUT);
    if result.ott.is_none() {
      log::warn!(target: "werewolf::auth", "loopback handoff on port {port} failed: {:?}", result.code);
    }
    let _ = app.emit(AUTH_CALLBACK_EVENT, result);
  });

  Ok(port)
}

#[cfg(test)]
mod tests {
  use super::*;

  /// Bind a loopback listener the way the command does.
  fn bound() -> (TcpListener, u16) {
    let listener = TcpListener::bind(SocketAddrV4::new(Ipv4Addr::LOCALHOST, 0)).unwrap();
    let port = listener.local_addr().unwrap().port();
    listener.set_nonblocking(true).unwrap();
    (listener, port)
  }

  /// Make a real HTTP request to the listener and return its status line.
  fn get(port: u16, target: &str) -> String {
    let mut stream = std::net::TcpStream::connect(("127.0.0.1", port)).unwrap();
    write!(stream, "GET {target} HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n").unwrap();
    stream.flush().unwrap();
    let mut line = String::new();
    BufReader::new(&stream).read_line(&mut line).unwrap();
    line.trim_end().to_string()
  }

  const NONCE: &str = "abcdefghijklmnopqrstuvwxyz012345";

  #[test]
  fn the_done_page_follows_the_app_locale_not_the_browser() {
    let spanish = done_page("es");
    assert!(spanish.contains("lang=\"es\""), "{spanish}");
    assert!(spanish.contains("Sesión iniciada"), "{spanish}");
    let english = done_page("en");
    assert!(english.contains("lang=\"en\""), "{english}");
    assert!(english.contains("Signed in"), "{english}");
    // Anything we do not ship falls back to English rather than rendering blank.
    assert!(done_page("fr").contains("Signed in"));
  }

  #[test]
  fn the_listener_binds_loopback_only() {
    let (listener, _) = bound();
    // Anything other than 127.0.0.1 here would expose a token-accepting
    // endpoint to the whole network.
    assert_eq!(listener.local_addr().unwrap().ip().to_string(), "127.0.0.1");
  }

  #[test]
  fn a_matching_callback_yields_the_token() {
    let (listener, port) = bound();
    let worker =
      thread::spawn(move || serve_once(&listener, NONCE, "en", Instant::now() + Duration::from_secs(5)));
    let status = get(port, &format!("/callback?ott=tok123&state={NONCE}"));
    assert!(status.contains("200"), "{status}");
    assert_eq!(worker.join().unwrap(), AuthCallback::token("tok123".to_string()));
  }

  #[test]
  fn a_wrong_nonce_is_refused_and_the_listener_keeps_waiting() {
    let (listener, port) = bound();
    let worker =
      thread::spawn(move || serve_once(&listener, NONCE, "en", Instant::now() + Duration::from_secs(5)));

    // Another local process guessing at our callback: refused, and crucially
    // it must not consume the one callback we are waiting for.
    let refused = get(port, "/callback?ott=attacker-token&state=wrong-nonce-wrong-nonce-wrong");
    assert!(refused.contains("403"), "{refused}");
    // A stray probe is likewise answered and ignored.
    let ignored = get(port, "/favicon.ico");
    assert!(ignored.contains("404"), "{ignored}");

    let accepted = get(port, &format!("/callback?ott=real-token&state={NONCE}"));
    assert!(accepted.contains("200"), "{accepted}");
    assert_eq!(worker.join().unwrap(), AuthCallback::token("real-token".to_string()));
  }

  #[test]
  fn a_server_side_error_is_passed_through() {
    let (listener, port) = bound();
    let worker =
      thread::spawn(move || serve_once(&listener, NONCE, "en", Instant::now() + Duration::from_secs(5)));
    get(port, &format!("/callback?error=UNAUTHENTICATED&state={NONCE}"));
    assert_eq!(worker.join().unwrap(), AuthCallback::failed("UNAUTHENTICATED"));
  }

  #[test]
  fn the_listener_gives_up_rather_than_waiting_forever() {
    let (listener, _port) = bound();
    let result = serve_once(&listener, NONCE, "en", Instant::now() + Duration::from_millis(150));
    assert_eq!(result, AuthCallback::failed("HANDOFF_TIMEOUT"));
  }

  #[test]
  fn constant_time_eq_matches_only_identical_strings() {
    assert!(constant_time_eq("abc", "abc"));
    assert!(!constant_time_eq("abc", "abd"));
    assert!(!constant_time_eq("abc", "ab"));
    assert!(!constant_time_eq("", "a"));
    assert!(constant_time_eq("", ""));
  }

  #[test]
  fn parse_callback_reads_the_token_and_the_nonce() {
    let (ott, state, error) = parse_callback("/callback?ott=tok123&state=nonce456");
    assert_eq!(ott.as_deref(), Some("tok123"));
    assert_eq!(state.as_deref(), Some("nonce456"));
    assert_eq!(error, None);
  }

  #[test]
  fn parse_callback_percent_decodes() {
    // Better Auth tokens are alphanumeric today, but the server
    // encodeURIComponent's them, so decoding must not be assumed away.
    let (ott, _, _) = parse_callback("/callback?ott=a%2Bb%2Fc%3D&state=n");
    assert_eq!(ott.as_deref(), Some("a+b/c="));
  }

  #[test]
  fn parse_callback_reads_an_error_instead() {
    let (ott, state, error) = parse_callback("/callback?error=UNAUTHENTICATED&state=n");
    assert_eq!(ott, None);
    assert_eq!(state.as_deref(), Some("n"));
    assert_eq!(error.as_deref(), Some("UNAUTHENTICATED"));
  }

  #[test]
  fn parse_callback_ignores_unrelated_requests() {
    let (ott, _, error) = parse_callback("/favicon.ico");
    assert_eq!(ott, None);
    assert_eq!(error, None);
  }
}
